sudo: required
services:
    - docker
before_install:
  - docker build -t rezaei/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rezaei/react-test npm test -- --coverage

after_success:
  - docker build -t rezaei/multi-client ./client
  - docker build -t rezaei/multi-nginx ./nginx
  - docker build -t rezaei/multi-server ./server
  - docker build -t rezaei/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"

  # take image and push to docker hub